Python/physics/mixei87/5
PS11011010/The-programmer-only-has-a-path pull request #10
Opened 2021-09-19 05:03 UTC by mixei87

2021-09-19 16:11 UTC, mixei87 commented
This request pull for task 5 about 3 resistors

2021-09-21 06:49 UTC, PS11011010 requested changes
Нужно пару комментов написать

2021-09-21 06:49 UTC, PS11011010 commented on Python/src/physics/common_resistance.py
> +    sum = R1 + R2
Тут неплохо бы формулу привести. А то математика без объяснения. Можно ссылку на википедию, стековерфлоу, если эта страница объясняет участок кода.

2021-09-21 06:49 UTC, PS11011010 commented on Python/src/physics/common_resistance.py
> +'''
укажи автора
@author [имя аккаунта гитхаб]

2023-02-01 11:09 UTC, closed without merging